<%@ page contentType="text/html; charset=UTF-8"%>
  <div class="foot">
    <ul style="margin-top:-10px;">
      <a href="#">人才招聘 |</a> <a href="#">联系我们 |</a> <a href="#">网站使用条款 |</a> <a href="#">隐私保护 </a>
    </ul>
    <p style="margin-top:5px;"> Copyright 2010-2011 MMB.CN All Rights Reserved</p>
    <p style="margin-top:-18px;">无锡买卖宝信息技术有限公司www.maimaibao.com版权所有 苏B2-20100287</p>
  </div>
</div>
</body>
</html>